### ISSUE TITLE
Images Server - assets.maocanhua.cn 

### ISSUE THREAD

**Issue by promediastyle** [m-Ryan/easy-email#15]
Tell me please.
In order to make the same server for pictures   -  https://assets.maocanhua.cn 
what do I need to use?

Is this ?  -  https://github.com/m-Ryan/v2ex-miniprogram-backend

**Comment by m-Ryan** [comment]
You can use AWS or GCP storage. My picture backend is just a proxy.

**Comment by promediastyle** [comment]
Could you help and do a little documentation on how to do it?
