### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by zaslavskyv** [m-Ryan/easy-email#21]
Is it possible to localize the email editor?

**Comment by m-Ryan** [comment]
The current version does not support.
Future versions will be disassembled in the form of plug-ins and you can write simple plug-ins to overwrite the UI.

![image](https://user-images.githubusercontent.com/20615214/142571254-20747f36-94fc-4ab3-9526-aaf195df466c.png)

**Comment by zaslavskyv** [comment]
Thank you for the answer, looking forward to the version that introduces this, please feel free to close the issue.
