### ISSUE TITLE
Make TextToolbar appear near the text control initially

### ISSUE THREAD

**Issue by zaslavskyv** [m-Ryan/easy-email#22]
The toolbar is displayed somewhere above the editable area by default:

<img width="809" alt="Screen Shot 2021-11-18 at 09 59 50" src="https://user-images.githubusercontent.com/83005319/142383935-bad79dae-8d11-4afc-918a-0bb0f2d15b4b.png">

Is it possible to display it near the text control it's invoked for?

**Comment by m-Ryan** [comment]
This was the case before, but someone suggested that it is not convenient to edit when switching between multiple texts.
And you can drag the toolbar to where you want

**Comment by zaslavskyv** [comment]
Thank you for the answer. Is it possible to set/override the default position so that the toolbar appears within the editor itself?

The problem is that in our case there's no upper panel with the buttons (and the editor is in an IFrame) — so the toolbar is almost invisible to the users because it's cut off.

**Comment by m-Ryan** [comment]
This should not be a very common problem。
The location information of the textbar is stored in localstorage, you can set it first. Like this
```js
localStorage.setItem("TEXT_BAR_LOCATION_KEY", JSON.stringify({"left":360,"top":447}))
```

**Comment by zaslavskyv** [comment]
Thank you!
