### ISSUE TITLE
Override default images

### ISSUE THREAD

**Issue by zaslavskyv** [m-Ryan/easy-email#23]
Is it possible to override images from the `IMAGE_LIST`, e.g. so that the picture component is displayed with a different image in the edit area by default?

**Comment by m-Ryan** [comment]
Export `IMAGE_LIST ` will release a new version later

**Comment by zaslavskyv** [comment]
Thank you for the answer, looking forward to the new version, please feel free to close the issue.

**Comment by m-Ryan** [comment]
Released 2.2.2.
https://github.com/m-Ryan/easy-email/commit/41f13eb9d2b36e7fd3cc4d0b9006e035b3e53ad1

**Comment by zaslavskyv** [comment]
Thank you, but it seems like the published version does not have this change.
