### ISSUE TITLE
Attempted import error: 'BlocksMap' is not exported from 'easy-email-editor'.

### ISSUE THREAD

**Issue by akhilWorkLand** [m-Ryan/easy-email#26]
I installed this into my react project I was following the documentation but when I tried to run it. I got  
Failed to compile.

./src/App.js
Attempted import error: 'BlocksMap' is not exported from 'easy-email-editor'.

I went to node modules and I found easy-email-editor folder inside that I was unable to find it. It's missing from the default exports. Did you guys replaced it with another name?

**Comment by m-Ryan** [comment]
Sorry, please install easy-email-editor@2.2.2. Due to my mistake, a beta version became the latest version.

**Comment by vasilevich** [comment]
@m-Ryan also  transformToMjml is no longer exported in version 2.5  ,  please give alternatives as it is very helpful in exporting html

Thank you so much!

**Comment by vasilevich** [comment]
@m-Ryan  are mergeTags supported? if so, since which version?  they seem not to work on @2.2.2 unfortunately the documentation does not state since what version they do ?

**Comment by shalb2018** [comment]
Also missing in the usage file at the end:

export default App

and don`t forget to put a semikolon after the last bracket  (like so: .....}; export default App)

Thanks for this great script!

**Comment by m-Ryan** [comment]
> @m-Ryan also transformToMjml is no longer exported in version 2.5 , please give alternatives or re-export, as it is very helpful in exporting html
> 
> Thank you so much!

Please not use the latest version, I am still doing more testing for it. It will take about two or three days

https://github.com/m-Ryan/easy-email/tree/mono-repo/packages/easy-email-core
`transformToMjml` will be rename to `JsonToMjml `

![image](https://user-images.githubusercontent.com/20615214/143515734-1a06338e-739a-4062-8a5c-3bb45c57542f.png)
