### ISSUE TITLE
Missing Export etc.

### ISSUE THREAD

**Issue by shalb2018** [m-Ryan/easy-email#27]
Hello, I installed the app accordingly to your installation procedure but the installation is missing parts, that I see in the Demo version, as there are.

1. I do not have any menu in the editor (the icons on top of the canvas).
2. I do  not have the buttons Export html, Send Test Mal and Save. How can I achieve these?

Thank you in advance.

Stefan

**Comment by zaslavskyv** [comment]
Hi,

1. If you're talking about the text toolbar, then you probably have the same problem as I did: https://github.com/m-Ryan/easy-email/issues/22
2. They are implemented in the `/example` directory: https://github.com/m-Ryan/easy-email/blob/e085bfb06641523bbe9921515691578574adfe5d/example/pages/Editor/index.tsx#L226-L257

HTH.

**Comment by m-Ryan** [comment]
> Hello, I installed the app accordingly to your installation procedure but the installation is missing parts, that I see in the Demo version, as there are.
> 
> 1. I do not have any menu in the editor (the icons on top of the canvas).
> 2. I do  not have the buttons Export html, Send Test Mal and Save. How can I achieve these?
> 
> Thank you in advance.
> 
> Stefan

Please check the version.
Do not instal the beta version, you can install easy-email-editor@2.2.2
And see simple demo here [https://github.com/m-Ryan/easy-email-demo](https://github.com/m-Ryan/easy-email-demo)

**Comment by shalb2018** [comment]
I installed the version 2.2.2, but I do not have there the folder examples. I am a bit lost, because otherwise the app works and I don`t know, where to put the mentioned file/code.

**Comment by m-Ryan** [comment]
> I installed the version 2.2.2, but I do not have there the folder examples. I am a bit lost, because otherwise the app works and I don`t know, where to put the mentioned file/code. Should I install anything from the easy-email-demo?

![image](https://user-images.githubusercontent.com/20615214/143587098-0a845d2b-ec25-4f34-82ec-8280f6ebbdb7.png)
Email-editor just a email container without any menu,  you can refer to how it is done.
 [https://github.com/m-Ryan/easy-email-demo/blob/main/src/App.tsx#L121-L136](https://github.com/m-Ryan/easy-email-demo/blob/main/src/App.tsx#L121-L136)

**Comment by shalb2018** [comment]
on build I always get this error:
```
G:/React Projects/easy-email-editor/src/mjml-browser.ts
TypeScript error in G:/React Projects/easy-email-editor/src/mjml-browser.ts(7,11):
'>' expected.  TS1005

     5 |
     6 |
  >  7 | <!DOCTYPE html>
       |           ^
     8 | <html lang="en" data-color-mode="auto" data-light-theme="light" data-dark-theme="dark">
     9 |   <head>
    10 |     <meta charset="utf-8">
```

**Comment by m-Ryan** [comment]
Let me see how you use it，`data-color-mode="auto" data-light-theme="light" data-dark-theme="dark`，where did these come from？
