### ISSUE TITLE
Delete Default Tamplates

### ISSUE THREAD

**Issue by thefubon** [m-Ryan/easy-email#8]
Please tell me. How do I delete the standard templates that are for example?
<img width="2204" alt="Снимок экрана 2021-08-31 в 22 13 43" src="https://user-images.githubusercontent.com/43171309/131562447-9b77a2b6-0e32-40ce-a23a-e140cb6852f6.png">

**Comment by thefubon** [comment]
How to make the database of patterns displayed on my server and not saved by you? As I understand it is just an assembly based on the Api which is on your server?

**Comment by m-Ryan** [comment]
> Please tell me. How do I delete the standard templates that are for example?
> <img alt="Снимок экрана 2021-08-31 в 22 13 43" width="2000" src="https://user-images.githubusercontent.com/43171309/131562447-9b77a2b6-0e32-40ce-a23a-e140cb6852f6.png">


You should use your email template instead of modifying mine. If you have a backend, you can get data from your backend Api

**Comment by m-Ryan** [comment]
> How to make the database of patterns displayed on my server and not saved by you? As I understand it is just an assembly based on the Api which is on your server?

The easiest way is to store the latest value, like axios.post\<IEmailTemplate\>('your api address', values). Then axios.get\<IEmailTemplate\>('your api address')

```ts
 interface IEmailTemplate {
  content: IPage;
  subject: string;
  subTitle: string;
}

```

**Comment by thefubon** [comment]
Please tell me how to use your API. And how can I create my own backend? I have only this archive. Could you make a video tutorial on how to do the same as yours? I am willing to pay for it.

<img width="1633" alt="Снимок экрана 2021-09-01 в 10 41 56" src="https://user-images.githubusercontent.com/43171309/131632478-8c156f7a-ab96-4945-97a7-773c266b6ef0.png">

**Comment by m-Ryan** [comment]
> Please tell me how to use your API. And how can I create my own backend? I have only this archive. Could you make a video tutorial on how to do the same as yours? I am willing to pay for it.
> 
> <img alt="Снимок экрана 2021-09-01 в 10 41 56" width="1633" src="https://user-images.githubusercontent.com/43171309/131632478-8c156f7a-ab96-4945-97a7-773c266b6ef0.png">

If you just need a test account, I can provide another one. But only for personal use.

**Comment by thefubon** [comment]
This is going to be very cool! I have five or six standard templates. In which I only change the text and the title picture. If it is possible to make a separate access for this . It would be very convenient.  

I also added a suggestion to update the demo version. This solution would be useful for many people. Because it does not use your resources

**Comment by m-Ryan** [comment]
> This is going to be very cool! I have five or six standard templates. In which I only change the text and the title picture. If it is possible to make a separate access for this . It would be very convenient.
> 
> I also added a suggestion to update the demo version. This solution would be useful for many people. Because it does not use your resources

Thanks for your feedback, I will update the demo later. And I will write a document later on how to create and use a test account.

**Comment by thefubon** [comment]
Thank you so much! You are the best!

**Comment by m-Ryan** [comment]
> This is going to be very cool! I have five or six standard templates. In which I only change the text and the title picture. If it is possible to make a separate access for this . It would be very convenient.
> 
> I also added a suggestion to update the demo version. This solution would be useful for many people. Because it does not use your resources

The document has been updated, see the doc [How to use an test account.md](https://github.com/m-Ryan/easy-email/blob/master/How%20to%20use%20an%20test%20account.md).

**Comment by thefubon** [comment]
https://github.com/m-Ryan/easy-email/blob/master/How%20to%20use%20an%20test%20account.md

There is an uncomfortable difficulty. There is no English language ;)

**Comment by m-Ryan** [comment]
> https://github.com/m-Ryan/easy-email/blob/master/How%20to%20use%20an%20test%20account.md
> 
> There is an uncomfortable difficulty. There is no English language ;)

Updated a version, now you just need to run `yarn account`

**Comment by thefubon** [comment]
As I understand it. You are using your CMS Ryan for the backend. If you install it, will it be possible to connect easy email to it ? And fully assemble it in your place like you do?

**Comment by m-Ryan** [comment]
> As I understand it. You are using your CMS Ryan for the backend. If you install it, will it be possible to connect easy email to it ? And fully assemble it in your place like you do?

Yes, try it.

**Comment by thefubon** [comment]
I tried, but I do not understand how to connect to another server. And as I understand it will not work in Versel? Only VDS?

**Comment by m-Ryan** [comment]
Why do you need to connect to another server? You only need to deploy static resources to Vercel.

**Comment by thefubon** [comment]
I wanted to do the same as you, only that all data - the paths to the images and JSON with templates stored on my server.

**Comment by thefubon** [comment]
It may be difficult. But it would be convenient6 for storing templates or files to have FTP or MySQL settings. As an additional option. What is now with yarn account is already ideal. But in my case really lacks the ability to store images and templates just by FTP

**Comment by m-Ryan** [comment]
> It may be difficult. But it would be convenient6 for storing templates or files to have FTP or MySQL settings. As an additional option. What is now with yarn account is already ideal. But in my case really lacks the ability to store images and templates just by FTP

Looks like I can’t help you, you need a backend server.

**Comment by thefubon** [comment]
I have a backand-forth server. But I don't have a opiate to set it up. Helping with its configuration and raising your engine on it will probably be inappropriate. But if you could help me. I would give you all the access

**Comment by thefubon** [comment]
Please tell me if I have a template that I built. How to make it not deleteable. I need 2-3 as standard.

**Comment by m-Ryan** [comment]
> lease tell me if I have a template that I built. How to make it not deleteable. I need 2-3 as standard.

Use another account.

**Comment by m-Ryan** [comment]
Try it.

window.setUser({
  phone: "12345679102", // your phone
  password: "yourpassword", // your password
  categoryId: 104, // your category id
});

**Comment by thefubon** [comment]
I did, about the fact that I need to make my 3 templates unremovable. Just like you have done, so that my colleagues did not accidentally delete my 3 starting templates.

**Comment by m-Ryan** [comment]
Let your colleagues use another account.

**Comment by thefubon** [comment]
I realized how easy it was to solve this problem. I noticed that there is a missing button, make a duplicate. Delete/Edit/Duplicate. Then it will be easier to work with templates without breaking already created ones

**Comment by m-Ryan** [comment]
> I realized how easy it was to solve this problem. I noticed that there is a missing button, make a duplicate. Delete/Edit/Duplicate. Then it will be easier to work with templates without breaking already created ones

Vsersion updated, now you can duplicate the template.

**Comment by thefubon** [comment]
Cool. Noticed a single bug. When a copy is created by writing a new header, it doesn't change.

**Comment by m-Ryan** [comment]
> n a copy is created by writing a new header, it

Thank you. Fix it now.

**Comment by thefubon** [comment]
Probably the last improvement I would like to say. I use the free vercel. You can't create closed access in it. And it turns out that anyone can come in and delete all my templates. I think there is not enough simple access by password. And the code would be chronicled in the env file. and add a login page.

**Comment by thefubon** [comment]
I made closed access through htaccess on the shared hosting. But there is a problem with the page router. Since it is not created after building the file editor.html then after reloading the page becomes 404. In Vercel everything works as it should. Only there is no more closed access to the editor

**Comment by m-Ryan** [comment]
![image](https://user-images.githubusercontent.com/20615214/132092913-27f13382-e307-4d71-8b62-a5fa54467f34.png)


Only need to change `createBrowserHistory` to `createHashHistory` In `example\util\history.ts`
